### ISSUE TITLE
DjangoとReactの連携方法考える

### ISSUE THREAD

**Issue by taxio** [StudioAquatan/mizql#1]

**Comment by taxio** [comment]
https://qiita.com/namutaka/items/da5db3ef6efcfebf43c8#javascript%E3%81%A8%E9%80%A3%E6%90%BA

https://github.com/vintasoftware/django-react-boilerplate/

https://github.com/owais/django-webpack-loader

**Comment by taxio** [comment]
面倒なのでwebpackの出力先をdjangoのstaticディレクトリにする．

**Comment by taxio** [comment]
buildした成果物をそのままnginxで配信するのが正解な気がしてきた。
そうすると、djangoアプリのディレクトリに書いてるのはおかしいから、ルートディレクトリに移動させる。

**Comment by pddg** [comment]
https://github.com/owais/django-webpack-loader

**Comment by taxio** [comment]
nginxでの配信がしっかりできたらclose

**Comment by pddg** [comment]
nodeのバージョン教えて

**Comment by taxio** [comment]
一応 `v11.1.0` だけど，あんまり関係ないかも

**Comment by pddg** [comment]
まぁ揃えとくほうが無難

**Comment by taxio** [comment]
https://github.com/StudioAquatan/mizql/blob/dev/frontend/.env.sample
`.env.production`と`.env.development`作らないといけない．

**Comment by pddg** [comment]
それはビルドに必要？

**Comment by taxio** [comment]
webpackのときに埋め込まれるから必要

**Comment by pddg** [comment]
理解．
